alfa-laboratory/arui-scripts

commands/docker-build/index.js

Добавил права доступа к файлу (чтение и выполнение) при создании start.sh скрипта
```/bin/sh: ./start.sh: Permission denied```

fix(*): add file mode while writing the start.sh file

---

configs/webpack.client.prod.js

see https://github.com/alfa-laboratory/arui-presets/pull/232

fix(webpack-client-prod): keep keyframes names

---

README.md
configs/postcss.config.js
configs/postcss.js

Пример использования
```
const {
createPostcssConfig,
postcssPlugins,
postcssPluginsOptions,
} = require('arui-scripts/configs/postcss.config');
module.exports = {
postcss: () => {
const newOption = {
...postcssPluginsOptions,
'postcss-import': {
...postcssPluginsOptions['postcss-import'],
path: [...postcssPluginsOptions['postcss-import'].path, './src'],
},
};
return createPostcssConfig(postcssPlugins, newOption);
},
};
```

improve postcss overrides

---

bin/index.js
commands/postinstall/index.js
package.json

```diff
-import { getOrganizationAccounts } from '../../actions/accounts';
+import { getOrganizationAccounts } from '@/src/actions/accounts';
-import { getNps } from '../../actions/nps';
+import { getNps } from '@/src/actions/nps';
-import { trackAlfaMetrics } from '../../actions/app';
+import { trackAlfaMetrics } from '@/src/actions/app';
-import { getGlobalNotification } from '../../actions/global-notification';
+import { getGlobalNotification } from '@/src/actions/global-notification';
-import { getFifaActionInfo } from '../../actions/fifa';
+import { getFifaActionInfo } from '@/src/actions/fifa';
```
```console
lrwxr-xr-x  1 farewell  staff  2 Oct  3 21:25 node_modules/#@ -> ..
```
1. Относительные пути ломаются при рефакторинге (перемещении) модулей;
2. Относительные пути вида …

ADD SYMLINK TO THE PROJECT ROOT FOLDER [CODE_REVIEW]

---

configs/webpack.client.prod.js

Удаляем лишние коменты из прод билда клиентского кода. Сейчас там куча лишних коментов

fix(webpack.client): remove pathinfo from client prod build

---

configs/.browserslistrc

Убираем префиксы для старых мертвых браузеров. Сейчас мы фактически таргетимся на всякий старых хлам типа QQ Browser1.2

feat(browserlist): forget dead browsers

---

README.md
configs/webpack.client.prod.js
package.json
yarn.lock

После миграции на 4-ю версию webpack, на некоторых проектах перестала работать сборка production-версии серверного бандла. Проблема заключалась в стандартном минификаторе webpack (UglifyES - бранч от UglifyJS) подключаемого через плагин ```UglifyjsWebpackPlugin``` <img width="522" alt="1" src="https://user-images.githubusercontent.com/37327825/49482980-789ec080-f842-11e8-9155-b959bb28d1ae.png">
Проблема была решена переопределением в конфиге стандартного минификатора на Terser через ```terser-webpack-plugin``` который является форком от уже неподдерживаемого UglifyES. Но оказалось, что следующая минорная версия webpack (4.26.0) уже переключилась на этот же новый минификатор, чтобы он мог в ES6. Собственно отсюда и апдейт.
Плагин ```OptimizeCssAssetsPlugin``` по-умолчанию использует …

fix(webpack-minimizer): update webpack, disable z-index optimize

---

commands/test/index.js

Argument array is: ['node', 'arui-scripts', 'test', ...otherArguments], so `.slice(2)` takes 'test' argument as well. So provided files to be tested was ignored, and all tests have been run instead.

fix(test): Fixed argument handling to test provided files only

---

commands/docker-build/index.js

Убран  вызов .toLowerCase() на argValue в скрипте docker-build. Теперь имя docker image должно будет соответствовать переданным значениям.
**Мотивация и контекст**
Для сборки докер образа могут быть переданы параметры извне, затем по этим параметрам может происходить поиск созданного образа для дальнейших манипуляций. И если значения этих параметров внутри скрипта docker-build изменяются, то результат не будет соответствовать ожидаемому внешним окружением, не удастся найти образ по изначальным параметрам.

fix: remove toLowerCase() call on argValue from docker-build

---

commands/archive-build/index.js
commands/docker-build/index.js
templates/dockerfile.template.js
templates/nginx.conf.template.js
templates/start.template.js

* Вынес шаблоны в отдельную папку templates
* При сборке докер-контейнера, конфиг для nginx кладется не к конфигам nginx, а в src
* В скрипте start.sh он копируется к конфигам nginx в уже запущенном контейнере
* При сборке архива (через archive-build) в корень архива так же подкладываются start.sh и конфиг nginx
В результате этого, контент архива будет идентичен контенту папки src докер образа, а запускать их можно будет одинаковым образом

Sync contents of archive with contents of docker

---

commands/postinstall/index.js

Кажется, что если симлинк уже есть, то постинсталл не должен вываливать ошибку в лог. А заодно, стоит проверять, симлинк ли это вообще

More obvious error messages on symlink creation issues

---

configs/webpack.client.dev.js
configs/webpack.client.prod.js
configs/webpack.server.dev.js
configs/webpack.server.prod.js

Весь jsx превращается в вызовы React.createElement(...) при компиляции. 
То есть даже если у вас в файле нигде нету явного использования React - он должен быть заимпорчен. На данный момент даже если вы не добавляли импорт сами - он добавится с помощью WebpackProvidePlugin. 
Хочется это отключить, так как другие сборщики (например library-utils, через который либы собираются) не поддерживают такое поведение, и могут возникать не очень явные проблемы при переносе кода из проекта в либу (на проекте оно у меня работало, а тут перестало, как же так?!)
Собственно после убирания этого плагина вам придётся добавить явный импорт, если у вас его нету.

feat(webpack): remove React ProvidePlugin

---

__tests__/src/app.jsx
__tests__/src/css-module.pcss
configs/util/css-modules-local-ident.js
configs/webpack.client.dev.js
configs/webpack.client.prod.js
configs/webpack.server.dev.js
configs/webpack.server.prod.js

Если вдруг кто не знает что такое css-модули - [гугл в помощь](https://frontender.info/css-modules-part-1-need/).
Включил только для *.pcss файлов (многие редакторы по дефолту воспринимают это как postcss файлы). Для css включать не планируется, так как сломает существующие проекты, а делать это флагом не хочется.

feat(*): add css modules support for *.pcss files

---

commands/archive-build/index.js
configs/app-configs.js

в доке написано, что additionalBuildPath используется для сборки архива, но это не так, исправил

feat(*): additional build path

---

package.json

Перенес typescript в devDependencies и добавил typescript в peerDependencies.
Это позволит arui-scripts использовать ts с проекта, в который установлен arui-scripts и, соответственно, управлять версией ts.
Этот ПР вместо вот этого ПР:
https://github.com/alfa-laboratory/arui-scripts/pull/41

feature: custom typescript version

---

README.md
configs/app-configs.js

Иногда надо кое чего проверить, собрав приложение в докер или в архив,
Для этого мы изменяем package.json секция aruiScripts. Но потом забываешь вернуть все обратно
Предлагаю сделать возможность переопределять через env
```
ARUI_SCRIPTS_CONFIG="{\"serverPort\":3333}" yarn docker-build
```

feat(*): allow override scripts settings by env

---

package.json
yarn.lock

Подтянул версию TypeScript до актуальной.
Чтобы корректно проходились тесты с новой версией, добавил зависимость @types/node.
Список изменений в новой версии:
[https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html)

chore(deps): bump typescript from 3.5.1 to 3.7.3

---

configs/dev-server.js

Requests with dots in URL used to interpret as assets. It results to unexpected errors in some requests.

fix(config): change assets RegExp in proxy

---

__tests__/tsconfig.json
configs/jest/index.js

добавил динамический мапинг путей для jest из `tsconfig.ts` для случая использования алиасов https://github.com/alfa-laboratory/arui-scripts/issues/68

feat(jest): dynamic pass paths for jest from tsconfig for aliases

---

configs/jest/index.js

Текущий регексп триггерил на любой урл в котором хоть как-то есть test или spec
https://regex101.com/r/fOQqEY/1
Починил... теперь работает где нужно, а где не нужно не работает 
https://regex101.com/r/bhPbUS/2

bugfix(jest-config): fix test files regexp

---

configs/webpack.server.dev.js
configs/webpack.server.prod.js

Для корректной сборки и работы серверного скрипта добавил новые репозитории core-components и icons в nodejs externals whitelist

Add @alfalab/icons and core-components to nodejs externals whitelist

---

configs/postcss.config.js
configs/util/setup-postcss-custom-properties.js
package.json
yarn.lock

В `core-components` мы используем темизацию через css-переменные.
Предполагается, что компоненты можно будет стилизовать на проекте с помощью переопределения этих переменных.
```
:root {
--border-radius: 4px;
}
.component {
border-radius: var(--border-radius);
}
```
```
:root {
--border-radius: 100px;
}
```
Все компоненты, которые используют эту переменную - получат **скругление в 100px** 👏
В плагине `postcss-custom-properties` есть возможность указать источник для импорта переменных с помощью опции `importFrom`.
Оказалось, что эта возможность работает **некорректно**.
Переменные из `importFrom` **НЕ** переопределяют уже существующие переменные.
В данном кейсе скругление так и осталось бы равным **4px**.
- Было решено форкнуть последнюю версию `postcss-custom-properties` и сделать фикс, …

feat(*): css vars theming

---

package.json
yarn.lock

Новая версия позволяет подключать стили через тег link
[Breaking changes](https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md#breaking-changes)

chore(packages): update style-loader

---

commands/build/client.js

При использовании оверрайдов можно переопределить вебпак конфиги как массивы. Но при таком использовании даже при успешной сборке текущая реализация падает. Фиксим это

fix(webpack-client): work with array-style webpack configs correctly

---

.editorconfig
configs/app-configs.js
configs/util/check-node-version.js
configs/webpack.client.prod.js

Добавлена поддержка brotli. Будет работать если версия nodejs сборщика > 10. На меньших версиях будет статические архивы с brotli собираться не будут. 
Для современных браузеров будут отдаваться ассеты сжатые бротли, для старых - gzip.
Попробовал как работает на активном проекте, получилось примерно так:
```
gzip  br
vendor.js   217   161
main.js     38.5  31.5
vendor.css  65.7  52.7
main.css    7.1   6.1
Total       328.3 251.3
```

feat(client): add brotli support

---

.travis.yml

Проект теперь использует github actions. Смысла в поддержке двух ci нет

chore(travis): remove travis.yml

---

configs/util/install-sourcemap-support.js
configs/webpack.server.prod.js

Fixes #43 
Сделал пакет source-map-support опциональной зависимостью. Теперь серверная часть будет работать даже когда пакет не установлен

fix(webpack-server): source-map-support is now optional

---

configs/jest/index.js

В последних версиях arui-scripts в tsconfig используется target: esnext, что приводит к ошибкам (если тест файлы имеют расширение ts) в тестах при условии, что в них используются нововведения из ES2020, в частности nullish-coalescing-operator и optional-chaining. Вопрос можно решить донастройкой ts-jest в package.json отдельного взятого проекта, либо пробросив в defaultJestConfig в ts-jest babel конфиг, который и так используется в  arui-scripts, таким образом все будет заводится "из коробки" без дополнительных конфигураций в package.json проекта.

Минорное изменение для ts-jest конфига

---

README.md
configs/supporting-browsers.js

Нужно иметь возможность переопределять список поддерживаемых браузеров для проекта. Сейчас это можно сделать в `arui-scripts.overrides.js` только так:
```javascript
babelClient: (config) => {
config.presets[0][1].targets.browsers = ['my', 'browsers'];
return config;
}
```
Предлагаю упростить это до вот такого:
```javascript
supportingBrowsers: () => ['my', 'browsers'];
```

feat(supporting-browsers): add supporting-browsers to overrides

---

README.md
commands/util/check-required-files.js
configs/util/get-entry-point.js
configs/util/get-entry.js
configs/webpack.client.dev.js
configs/webpack.client.prod.js
configs/webpack.server.dev.js
configs/webpack.server.prod.js

Добавлена поддержка любых возможных конфигураций entryPoint, как серверной, так и клиентской.
Теперь через настройки в package.json можно передавать строку, массив, или объект с entryPoint

feat(webpack): add support for multiple entrypoints

---

configs/postcss.config.js
package.json
yarn.lock

На обсуждении было решено использовать `color-mod` для модификации цветов.
Хоть это и deprecated, но плагины под новую спеку еще сырые. 
`postcss-color-function` - не подходит под требования, т.к. у него есть проблемы с css-переменными и не поддерживаются некоторые функции, типа blenda.

feat(postcss-config): add postcss-color-mod-function

---

configs/webpack.client.dev.js
package.json
yarn.lock

postcss обрабатывает каждый файл отдельно, поэтому импорты переменных в каждом файле приводят к их дублированию и ~пиздецу~.
Одно из решений - сделать один бандл и оптимизировать его.
Для дев режима:
1. Заменил style-loader на MiniCssExtractPlugin, который объединяет стили в один файл.
2. OptimizeCSSAssetsPlugin прогоняет полученный бандл через cssnano, который удаляет дубли. Из cssnano оставил только discardDuplicates
Сорсмапы работают, но отображается не очень красивый путь:
Решение [тут](https://github.com/alfa-laboratory/arui-scripts/commits/refactor/replace-style-loader), но для этого нужно обновить css-loader, который требует уже 10ую ноду. 
Думаю кривой путь - не проблема, т.к. сейчас вообще просто пишется <style> и не отображаются строки

feat(webpack): replace style tags with optimized css bundle in dev

---

README.md
configs/app-configs.js
configs/postcss.config.js
package.json
yarn.lock

В кор-компонентах есть два варианта использования темизации - использование нативных переменных и транспайлинг через плагин.
Для упрощения настройки добавил возможность отключать плагин `postcss-custom-properties` с помощью опции `keepCssVars`.
В случае транспайлинга - можно быстро задать тему через `componentsTheme`.
Т.к. реквест в https://github.com/postcss/postcss-custom-properties был принят, то заменил форк на основной репозиторий.

feat(postcss-config): add keepCssVars, revert plugin

---

packages/arui-scripts/src/configs/webpack.server.dev.ts
packages/arui-scripts/src/configs/webpack.server.prod.ts

Исправляем осточертевший баг с конфликтом версии date-fns в проекте и в arui-feather. Теперь оба эти пакеты будут externals, так что резолвинг будет работать корректно

fix(webpack-server): add date-fns to externals

---

packages/arui-scripts/src/configs/webpack.client.dev.ts

Без этого в дев режиме не корректно грузятся картинки которые не попадают под размеры url-loader

fix(webpack-dev): add public path, so images loads correctly in dev mode

---

.pnp.js
packages/arui-scripts/package.json
packages/arui-scripts/src/configs/webpack.client.dev.ts
packages/arui-scripts/src/configs/webpack.client.prod.ts
yarn.lock

Используем для svg другой загрузчик. Основная идея - вместо того, чтоб представлять svg как base64 в data-url он представляется как svg. Ну только с добавлением энгодинга на некоторые символы.
Есть [пара](https://css-tricks.com/probably-dont-base64-svg/) [старых](https://codepen.io/tigt/post/optimizing-svgs-in-data-uris) статей на эту тему.
Собственно проверив на 1 проекте результаты прям хорошие получились:
До:
```
Assets sizes:
425.88 KB (76.3 KB gzip, 60.34 KB br)  vendor.css
49.8 KB (9.49 KB gzip, 8.41 KB br)  vendors~app-header.css
Total size:
475.68 KB (85.79 KB gzip, 68.75 KB br)
```
После:
```
Assets sizes:
392.31 KB (64.43 KB gzip, 49.88 KB br)  vendor.css
43.86 KB (7.78 KB gzip, 6.58 KB br)  vendors~app-header.css
Total size:
436.17 KB (72.21 KB gzip, 56.46 KB br)
```
в чистом …

feat(webpack-client): use svg-url-loader for svg

---

packages/arui-scripts/src/templates/nginx.conf.template.ts

Делаем так, чтоб nginx всегда использовал только ipv4 хост для поиска ноды. В некоторых случаях localhost внутри контейнера может разрезолвится в ipv6 адрес, nodejs обычно на ipv6 у нас не слушает, и в итоге мы можем получить 503 ошибку

fix(nginx): always use only ipv4 host

---

packages/arui-scripts/src/configs/dev-server.ts

`path.resolve` возвращает абсолютный путь, на Windows к нему добавляется имя диска в начале, что приводит к некорректному сравнению `req.url` и `assetsRoot`. Заменил `path.resolve` на `path.normalize`, т.к. слеш в начале пути уже указывает, что путь абсолютный и `path.resolve` просто нормализует путь. `path.normalize` не пытается сделать путь абсолютным, и не добавляет имя диска к пути на Windows.

fix(dev-server): fix wrong path and url comparison on windows

---

packages/arui-scripts/src/templates/dockerfile.template.ts

Когда собираем образ с флагом  "runFromNonRootUser": true - то получаем ошибку: chown: /var/lib/nginx: No such file or directory
Это ошибка воспроизводиться как локально так и в бамбу.
Скрин локальной сборки:
Скрин cборки bamboo:
--
После добавления mkdir -p (этот флаг означает, что если нет такой папки то нужно создавать) все работает корректно.

fix(*): fix folder error

---

packages/arui-scripts/src/templates/start.template.ts

Оказывается, в 12 ноде поменялось то, сколько памяти по дефолту выдкеляется под хип. Раньше дефолт был около 1400мб (для x64), что было логично для браузера, но странно для сервисов на nodejs. И они его поменяли, теперь вроде стало логично, nodejs стал передавать в v8 то, сколько памяти таки можно брать, причем даже с учетом лимитов от докера. Очень круто и логично. 
Но! У v8 есть еще и свой код, который в зависимости от максимально доступной памяти, ограничивает то, сколько можно выделить под хип.
Вот тут есть комент с подробным описанием, кратко - если у вас максимальный объем памяти <= 512мб - вам будет выделено 256мб. 
Поскольку большая часть наших фронтов запускают nodejs в докер контейнерах, с ограничением по памяти в 512мб нода у большинства из нас оказывается загнаной в весьма …

fix(nodejs): allow to use more memory on constrained environments

---

.pnp.js
packages/arui-scripts-test/package.json
packages/arui-scripts-test/src/style.css
packages/arui-scripts/package.json
packages/arui-scripts/src/commands/util/check-required-files.ts
packages/arui-scripts/src/configs/app-configs.ts
packages/arui-scripts/src/configs/config-type.ts
packages/arui-scripts/src/configs/util/__tests__/get-polyfills.tests.ts
packages/arui-scripts/src/configs/util/get-polyfills.ts
packages/arui-scripts/src/configs/webpack.client.dev.ts
packages/arui-scripts/src/configs/webpack.client.prod.ts
yarn.lock

На данный момент у нас по умолчанию сборка идет с сохранением css переменных в скомпиленом бандле. ie11 не умеет работать с переменными без полифила. Автоматически добавлем полифил тогда, когда в коде остаются css переменные.

fix(css-vars): add polyfill for ie11 when using css vars

---

packages/arui-scripts/release.config.js

Сейчас не работает публикация новых версий через semantic-release. Названия пререлизных версий строятся из названий веток, и туда затесался недопустимый символ. 
valid name for prerelease is described here: https://semver.org/#spec-item-9

chore(semantic-release): valid prerelease name

---

.github/workflows/nodejs.yml
packages/arui-scripts/package.json

Поддержка 10 ноды мешает развитию. Собственно 10 нода уже и не поддерживается.
Это BREAKING CHANGE.

feat(*): upgrade minimal nodejs version

---

packages/alpine-node-nginx/nginx.conf

До этого добавление версии было выключено на уровне server, но многие проекты используют кастомный nginx.conf и эта директива теряется. Поэтому отключаем ее совсем на уровне всего конфига nginx.
ps: доки по server_tokens https://nginx.org/ru/docs/http/ngx_http_core_module.html#server_tokens

fix(nginx): disable server tokens globaly

---

packages/arui-scripts/README.md
packages/arui-scripts/src/templates/start.template.ts

После добавления envsubst вылезла проблема. В некоторых проектах в конфигурации nginx содержатся специальные переменные nginx, типа `$proxy_add_x_forwarded_for`, и envsubst заменяет их на пустую строку, что делает конфигурацию невалидной.
Как обходной путь - предлагаю сделать так, чтоб envsubst заменял ТОЛЬКО переменные вида `${}`. Чтоб это заработало - строки вида `$[a-zA-Z0-9_-]` заменяются на `~~..~~`, потом прогоняется envsubst, потом строки возвращаются на место

fix(nginx): keep nginx special vars in place when using envsubst

---

packages/arui-scripts/src/templates/start.template.ts

sed работает построчно, пожтому несколько вхождений $переменных в файле он нормально реплейсил. Но Если в строке сразу несколько таких переменных - он реплейсил только первое вхождение

fix(start.sh): replace all nginx variables in line

---

packages/arui-scripts/src/configs/webpack.client.dev.ts

В [этом коммите](https://github.com/alfa-laboratory/arui-scripts/commit/204c743b6910d8ca75e60d3163f45f98fe615905) перенесли плагин в другую секцию, но забыли включить минификацию. Из-за этого в новой версии переменные стали дублироваться и случился 🔥 **css-vars-hell** 🔥

fix(webpack): restore css minimization in dev

---

packages/arui-scripts/src/configs/webpack.client.dev.ts
packages/arui-scripts/src/configs/webpack.server.dev.ts

Начиная с webpack 5 установка mode включает опцию [optimization.nodeEnv](https://webpack.js.org/configuration/optimization/#optimizationnodeenv) и устанавливает ее в то значение, какой mode собственно выбран. Это конфликтует с установкой node_env через [define plugin](https://github.com/alfa-laboratory/arui-scripts/blob/c03849a57b828f7c35f85b8062d7cb832983c797/packages/arui-scripts/src/configs/webpack.client.dev.ts#L247). В случае, если сборка будет запускаться с каким то значением env, отличным от development - будет включаться варнинг. Часть проектов использует node_env=cypress для запуска тестов, от этого ломаются тесты

fix(webpack-dev): disable default override of NODE_ENV
