alfa-laboratory/arui-scripts

configs/app-configs.js
Поправил настройку базового образа - иначе всегда будет добавляться heymdall/alpine-node-nginx:8.9.1
=> fix(app-configs): fix baseDockerImage

configs/app-configs.js
=> fix(app-configs): typo in serverPort

jest-preset.json
Добавлено cвойство testURL для JEST конфигурации
=> feat(jest-preset): add testURL

README.md, commands/docker-build/index.js, configs/app-configs.js, configs/util/apply-overrides.js, configs/webpack.client.prod.js
Добавил возможность использования собственного Dockerfile'а в проекте
=> feat(docker-build): added ability to override dockerfile

package.json, yarn.lock
Fix security issue https://nvd.nist.gov/vuln/detail/CVE-2018-14732
=> fix(dependencies): update webpack-dev-server

package.json, yarn.lock
Because issue https://github.com/webpack/webpack-dev-server/issues/1604
=> feat(webpack-dev-server): up version to 3.1.4

package.json, yarn.lock
Просто обновил версию тайпскрипта
=> chore(*): updated ts version

configs/webpack.client.prod.js
Используем для минификации TerserPlugin. Работает быстрее и эффективнее чем дефолтный аглифай.
=> feat(webpack.client.prod): use TerserPlugin for minimization

configs/webpack.server.dev.js, configs/webpack.server.prod.js
При сборке проекта возникают расхождения в названиях классов.
[https://ibb.co/qCW361v](url)
=> fix(*): fix postcss webpack server config

configs/app-configs.js, templates/nginx.conf.template.js
Добавил возможность задать путь к приложению в nginx на тот случай, если он раскатывается в контейнере. Не всегда это по дефолту src.
=> Add nginx config root path

README.md, __tests__/package.json, configs/app-configs.js
https://github.com/alfa-laboratory/arui-scripts/issues/56
единственное по поводу того какой оставить - у меня вопрос)
@SiebenSieben aruiScripts же популярнее по всем нашим репам?
=> chore(*): support only aruiScripts settings

commitlint.config.js, package.json, yarn.lock
=> Commitlint and husky

__tests__/yarn.lock, configs/webpack.client.prod.js, configs/webpack.server.dev.js, configs/webpack.server.prod.js, package.json, yarn.lock
1.0.1 версия не позволяет относительные пути для url в режиме modules: true.
а у нас css-modules
=> fix(*): up css loader

configs/jest/index.js
Пофиксил ишью https://github.com/alfa-laboratory/arui-scripts/issues/78
теперь все ок https://regex101.com/r/MgxMcN/1
=> fix(*): fix regexp to exclude test files outside of src dir

configs/util/css-modules-local-ident.js, configs/webpack.client.dev.js, configs/webpack.client.prod.js, configs/webpack.server.dev.js, configs/webpack.server.prod.js
https://github.com/alfa-laboratory/arui-scripts/issues/81
=> chore(*): use react dev utils instead of own pattern

.editorconfig
Добавил .editorconfig в проект.
=> feat(*): add .editorconfig

templates/nginx.conf.template.js
Увеличивыет client_max_body_size
=> fix(nginx.conf.template): updated rule for request's max body size

configs/app-configs.js
Обновляем базовый образ ноды для итоговых контейнеров
=> feat(config): use node 12 as default base image

configs/webpack.server.dev.js, configs/webpack.server.prod.js
Добавляем очередную либу.
Жду когда @Heymdall разресерчит этот момент
=> feat(*): add newclick-composite-components to whitelist

configs/tsconfig.json
Разрешает импортировать json-файлы из модулей
=> fix(tsconfig): allow import json modules

commands/docker-build/index.js, yarn.lock
Добавил возможность указать dockerRegistry через аргументы (надо для платформы).
=> feat(docker-build): fetch registry from args

README.md
https://github.com/alfa-laboratory/arui-scripts/issues/106
=> docs(*): fix default value in docs

README.md, configs/app-configs.js, configs/postcss.config.js
Мотивация: не тратить время на то, что бы понять почему не работает передаваемая настройка.
=> feat(config): check passed settings

configs/tsconfig.json
=> fix(tsconfig): disable removeComments flag

commands/util/client-assets-sizes.js, package.json, yarn.lock
=> feat(assets-size): print brotli size when possible

configs/app-configs.js, configs/util/validate-settings-keys.js
Небольшой рефакторинг работы с конфигом.
=> refactor(app-config): validate and read settings keys in the same way

README.md, __tests__/package.json, bin/index.js, commands/bundle-analyze/index.js, commands/util/make-tmp-dir.js, package.json, yarn.lock
Fixes #115
Добавляет отдельную команду для запуска bundle-analyzer
=> feat(webpack): add bundle-analyze command

package.json, yarn.lock
Этот плагин немного сломался, начиная с 8й версии 🤷‍♂️
- Пофиксил у нас в форке
- Добавил тестов
- Открыл им PR (но там активности нет)
Фиксит:
https://github.com/alfa-laboratory/arui-scripts/issues/113
https://github.com/postcss/postcss-custom-properties/issues/215
https://github.com/postcss/postcss-custom-properties/issues/218
https://github.com/postcss/postcss-custom-properties/issues/221
PR:
https://github.com/postcss/postcss-custom-properties/pull/222
Сам фикс:
https://github.com/postcss/postcss-custom-properties/pull/222/files#diff-69b99f148c450826ad29f0f59e55c702
=> fix(deps): update @alfalab/postcss-custom-properties

README.md
Исправление ссылок на разные файлы в документации
=> docs(*): fix links in documentation

.github/workflows/alpine-node.yml, packages/arui-scripts/package.json, packages/arui-scripts/tsconfig-local.json, packages/arui-scripts/tsconfig.json
Разделяем локальный билд конфиг, и тот, который используют потребители.
=> fix(tsconfig): separate build config from published config

.github/workflows/npm-publish.yml, .pnp.js, packages/arui-scripts/package.json, packages/arui-scripts/release.config.js, yarn.lock
Добавляем поддрежку автоматических релизов через semantic-release
=> feat(*): automatic releases

packages/arui-scripts/README.md
Исправление битых ссылок в ридми
=> docs(*): fix broken links

packages/arui-scripts/src/templates/start.template.ts
Папка куда распаковывается артифакт и с которой стартует выполнение может быть другой
=> fix(*): support custom start folder

packages/arui-scripts/src/templates/nginx.conf.template.ts
Всем привет,
добавил проксирование оригинального хоста в конфиг nginx, чтобы можно было не терять его при проксировании запроса.
=> feat(nginx): add original host to nginx template
